### ISSUE TITLE
How to install? [NotImplementedError]

### ISSUE THREAD

**Issue by ssj4000** [akej74/grid-control#2] opened 2016-10-06 00:08 UTC
I would like to know the step by step process to install because I am getting this error.
## An unhandled exception has occurred

class NotImplementedError
## Operation not supported or unimplemented on this platform

  File "grid-control\gridcontrol.py", line 705, in <module>
  File "grid-control\gridcontrol.py", line 64, in **init**
  File "grid-control\kraken.py", line 47, in **init**
  File "site-packages\usb\core.py", line 1025, in ctrl_transfer
  File "site-packages\usb\core.py", line 102, in wrapper
  File "site-packages\usb\core.py", line 120, in managed_open
  File "site-packages\usb\backend\libusb1.py", line 786, in open_device
  File "site-packages\usb\backend\libusb1.py", line 643, in **init**
  File "site-packages\usb\backend\libusb1.py", line 593, in _check

**Comment by akej74** [comment] 2016-10-06 11:28
Most likely caused by PyUSB not finding a "backend", investigation ongoing... Please also see discussion on [Reddit](https://www.reddit.com/r/NZXT/comments/55plsc/grid_control_now_with_experimental_kraken_x61/).

**Comment by ssj4000** [comment] 2016-10-06 14:23
I look forward to getting your grid-control up and running for all users, because NZXT CAM crashes all of my games... It even crashes itself, clearly it is poorly developed.

**Comment by akej74** [comment] 2016-10-07 11:41
Hi, as the Kraken experimental support seems to cause issues for some users, I will disable it by default and have an "enable" checkbox on the "Kraken" tab. Than way the Kraken support can be tested without affecting the Grid Control main functionality (i.e. controlling the Grid).

**Comment by ssj4000** [comment] 2016-10-07 17:32
Awesome! Looking forward to it.

**Comment by akej74** [comment] 2017-08-29 11:57
Closing as Kraken support is put on hold indefinitely.

**Closed as completed by akej74** 2017-08-29 11:57 UTC
